name = "sukisu-ultra"
compatibility_date = "2025-11-15"

pages_build_output_dir = "docs/.vitepress/dist"

[build]
command = "bun install && bun run build"

[env.production]
vars = { NODE_VERSION = "24", BUN_VERSION = "1.3.2" }